language: en
reviews:
  profile: chill
  request_changes_workflow: false
  poem: false
  high_level_summary: true
  review_status: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
  tools:
    gitleaks:
      enabled: true
    markdownlint:
      enabled: false
    shellcheck:
      enabled: false
    yamllint:
      enabled: false
    languagetool:
      enabled: false
chat:
  auto_reply: true
